package learn;

public class CelsiusConverterGUI extends javax.swing.JFrame
{
    
    /** Creates new form CelsiusConverterGUI */
    public CelsiusConverterGUI()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        celsiusTextField = new javax.swing.JTextField();
        fahrenheitTextField = new javax.swing.JTextField();
        celsiusLabel = new javax.swing.JLabel();
        fahrenheitLabel = new javax.swing.JLabel();
        convertButtonCelsiusToFahrenheit = new javax.swing.JButton();
        convertButtonFahrenheitToCelsius = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Celsius <==> Fahrenheit Converter");

        celsiusLabel.setText("Celsius");
        fahrenheitLabel.setText("Fahrenheit");

        convertButtonCelsiusToFahrenheit.setText("C ==> F");
        convertButtonCelsiusToFahrenheit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                convertCelsiusToFahrenheit(evt);
            }
        });

        convertButtonFahrenheitToCelsius.setText("F ==> C");
        convertButtonFahrenheitToCelsius.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                convertFahrenheitToCelsius(evt);
            }
        });

        getContentPane().setLayout(new java.awt.GridLayout(3,2));
        add(celsiusTextField);
        add(celsiusLabel);
        add(fahrenheitTextField);
        add(fahrenheitLabel);
        add(convertButtonCelsiusToFahrenheit);
        add(convertButtonFahrenheitToCelsius);

        pack();
    }

    private void convertCelsiusToFahrenheit(java.awt.event.ActionEvent evt)
    {
        int tempFahrenheit = (int)((Double.parseDouble(celsiusTextField.getText())) * 1.8 + 32);
        fahrenheitTextField.setText(tempFahrenheit + "");
    }

    private void convertFahrenheitToCelsius(java.awt.event.ActionEvent evt)
    {
        int tempCelsius = (int)((Double.parseDouble((fahrenheitTextField.getText())) - 32) / 1.8);
        celsiusTextField.setText(tempCelsius + "");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CelsiusConverterGUI().setVisible(true);
            }
        });
    }
    
    private javax.swing.JLabel celsiusLabel;
    private javax.swing.JLabel fahrenheitLabel;
    private javax.swing.JTextField celsiusTextField;
    private javax.swing.JTextField fahrenheitTextField;
    private javax.swing.JButton convertButtonCelsiusToFahrenheit;
    private javax.swing.JButton convertButtonFahrenheitToCelsius;
    
}